### ISSUE TITLE
API 설계도 구체화 및 분업

### ISSUE THREAD

**Issue by taerok** [gdg-team-1/backend#1]
구현 전에 디테일 잡고 그에 따라 분업하시면 될꺼 같습니다.

## 위치 정보 API
*  json 파일을 두개를 올려주셨습니다. id 넣어도 될꺼 같기도 하고 그냥 귀찮으니까 `서울시 종로구 사직동` 문자열 자체를 키로 써도 될꺼 같기도 하네요.

[1번]
```
{
  "korea": [
    "서울특별시": {
      "종로구": [
        "사직동",
          ...
        "혜화동"
      ],
      ...
```
[2번]
```
{
  "korea": [
    {
      "city_name": "서울특별시",
      "districts": [
        {
          "district_name": "종로구",
          "neighborhoods": [
            "사직동",
              ...
            "혜화동"
          ]
        },
        ...
```

*  장소를 기준으로 한다고 했으니 모든 알리바이에는 `location_id`가 추가되어야 할꺼 같아요.

## 알리바이 목록 API, 알리바이 요청 API
구현해야 될 항목이 다음과 같습니다.
* READ 3개(전체목록, 내 목록, 알리바이 디테일) 
* CREATE 1개(알리바이 1개 생성) 

솔직히 뭘 나눌지 싶습니다.... 얘기라도 해봅시다.

**Comment by jypthemiracle** [comment]
우선, DB를 어떤걸 쓰시느냐에 따라 ERD를 그릴 지 말지 고민해보면 될 것 같습니다.

**Comment by realsigridjin** [comment]
## gcloud 공부하기
* 퀵랩 평일에 보고 학습한다.
* 금~토요일 사이에 실제 서비스를 붙인다.

**Comment by taerok** [comment]
### 업무 분담
------

@taerok 
* 알리바이 API 서버 구축
* 추가 기능 탐색 및 구현(사진 관련 AI 기능 탐색중)

@jypthemiracle 
* 실 서비스를 고려한 아키텍처 설계
