### ISSUE TITLE
QwikLabs 학습 진척사항 + 추후 작업 내용

### ISSUE THREAD

**Issue by sigridjineth** [gdg-team-1/backend#2]
## 진척사항
* [x] ~7/7(수) Google Cloud Essentials 다 듣기
* [x] 7/8(목) Create and Manage Cloud Resources (Challenge Lab) 수료하기 [링크](https://www.qwiklabs.com/focuses/10258?parent=catalog)
* [ ] 7/8(목)~7/9(금) Baseline: Infrastructure 다 듣기 [링크](https://www.qwiklabs.com/quests/33?catalog_rank=%7B%22rank%22%3A3%2C%22num_filters%22%3A0%2C%22has_search%22%3Afalse%7D)
* [x] 7/9(금)~7/10(토) gdg-team-1 backend GCloud에 배포하자!

## 시간이 남는다면?
* [x] 7/10(토)~7/11(일) Docker & Kubernetes 적용하기
- Deploy and Manage Cloud Environments with Google Cloud [링크](https://www.qwiklabs.com/quests/121?catalog_rank=%7B%22rank%22%3A8%2C%22num_filters%22%3A0%2C%22has_search%22%3Afalse%7D)
- Gcloud에 배포(instance group + load balancer)

**Comment by realsigridjin** [comment]
GKE로 Load Balancer까지 설정해보면서 한 번 배포할 수 있었던 좋은 기회였습니다.
